CREATE TABLE exercise
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    training_id       BIGINT,
    exercise_category VARCHAR(150),
    CONSTRAINT pk_exercise PRIMARY KEY (id)
);

CREATE TABLE training
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_training PRIMARY KEY (id)
);

ALTER TABLE exercise
    ADD CONSTRAINT FK_EXERCISE_ON_TRAINING FOREIGN KEY (training_id) REFERENCES training (id);